### ISSUE TITLE
Golang version of Yamp?

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/yamp#8]
We want a Golang version of Yamp because

1. it can be incorporated into Go programs like Helm and Kubernetes operators etc which are normally written in Golang
2.  it runs much faster
3. it has a single binary per platform to make installation easy.

**Comment by birchb1024** [comment]
Goyamp work has started and it is running most of the Yamp examples now. Plenty of bugs and refactorings still to be done. The code is in [github goyamp repo](https://github.com/birchb1024/goyamp) , currently private. Hands up who wants a pre-alpha preview?

**Comment by kingdase** [comment]
Yes, I would like to try Goyamp.

**Comment by birchb1024** [comment]
The code is ordinary right now, I have not been writing Golang for long. Coverage only 71%
 I can push up a docker image with the binary in it soonish.

**Comment by birchb1024** [comment]
You may please try the docker image: https://cloud.docker.com/repository/docker/birchb1024/goyamp)

Regards,
Peter

**Comment by birchb1024** [comment]
A new goyamp image has been built (0.0.4)

**Comment by birchb1024** [comment]
Compare the speed! When running all-examples.yaml 
Yamp (Python)  - 30 files
real    0m1.307s
user    0m0.648s
sys     0m0.068s

Goyamp (Go) - 20 files
real    0m0.030s
user    0m0.016s
sys     0m0.012s

That works out at 14 times faster.

**Comment by kingdase** [comment]
Hi Peter,
the latest docker image works with our main pipeline.yamp (about 1500 lines - contains macros; flatten on several levels along with repeat; python_eval; if statements ...).
Advantage: the go version performs a more accurate yaml syntax check - the concourse yaml interpreter is a bit sloppy ...

So we could already switch to the go version.
Do you have a schedule for unlocking the go repository?

Thanks again for your great work and support !

Kind regards 
Jens

**Comment by birchb1024** [comment]
Hi,
The Go code now is much better structured. I am poised to open the repo. There is a a bunch of documentation work needed. The latest build 0.1.1 has some new features:

- `__VERSION__` variable give the goyamp version
- `panic:` exits the program abruptly. useful for defining asserts in macros.
- Go package and API

**Comment by birchb1024** [comment]
Goyamp is now public. https://github.com/birchb1024/goyamp
Latest release is 0.1.3

```
$ curl -L -o goyamp https://github.com/birchb1024/goyamp/releases/download/0.1.3/goyamp
$ chmod a+x goyamp
```
This issue therefore closed.
